[package]
name = "konwerter-gui"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10.0"
konwerter ={ git = "https://github.com/FraI3mega/konwerter.git"}
